### ISSUE TITLE
Support for scrivener_ecto ~> 2.0?

### ISSUE THREAD

**Issue by davidliang781205** [stephenmoloney/scrivener_list#4]
Is support for scrivener_ecto ~> planned?

Using ecto 3.0.4

Thanks in advance!

**Comment by PhillippOhlandt** [comment]
I just wanted to install this package but I can't because I use `ecto` 3 and this package requires `scrivener_ecto` which needs `ecto` 2.

**Comment by stephenmoloney** [comment]
I made a new release 2.0.0 for this, see #5
